### ISSUE TITLE
hi ,you build mpv is awesome, very very nice , it can run every where ,and awlway show all fonts

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/MPV_AppImage#1]
can you pull the build file , yaml and workflow

i not see it

and the font can show it, very normaly
![image](https://github.com/lucasmz1/MPV_AppImage/assets/87791643/c5d75bfe-f0c9-41d5-bb23-b68b69b6680e)

**Comment by lucasmz1** [comment]
thank you!
